CHANGELOG.md, docs/controller_provider.md, src/frontend/demo/package.json, src/frontend/demo/src/App.test.tsx, src/frontend/demo/src/index.tsx, src/frontend/magnify/.storybook/preview.js, src/frontend/magnify/package.json, src/frontend/magnify/src/components/TestButton/TestButton.test.tsx, src/frontend/magnify/src/components/TestButton/TestButton.tsx, src/frontend/magnify/src/controller/ControllerProvider.tsx, src/frontend/magnify/src/controller/default.controller.ts, src/frontend/magnify/src/controller/index.ts, src/frontend/magnify/src/controller/interface.ts, src/frontend/magnify/src/controller/log.controller.ts, src/frontend/magnify/src/controller/mock.controller.ts, src/frontend/magnify/src/controller/mocks/example.ts, src/frontend/magnify/src/index.ts, src/frontend/package.json, src/frontend/yarn.lock
The goal of this PR is to introduce tools to make api calls from the components, in a way that can easily be overriden by the developers using the lib, by using a dependency injection patern
This PR introduce following components
- A provider, to wrap the app in
- 3 controllers : a mock for the storybook (console.log + fixtures), , a mock for tests (jest.fn), and a controller to call the api
- a hook to get the controller
And demonstrate how to use them in component TestButton and its tests
=> Create an abstraction for calling the api

CHANGELOG.md, src/frontend/demo/package.json, src/frontend/magnify/.storybook/preview.js, src/frontend/magnify/.storybook/theme.js, src/frontend/magnify/package.json, src/frontend/magnify/src/components/design-system/LoadingButton/LoadingButton.stories.tsx, src/frontend/magnify/src/components/design-system/LoadingButton/LoadingButton.test.tsx, src/frontend/magnify/src/components/design-system/LoadingButton/LoadingButton.tsx, src/frontend/magnify/src/components/design-system/LoadingButton/index.ts, src/frontend/magnify/src/components/design-system/index.ts, src/frontend/magnify/src/components/index.ts, src/frontend/magnify/src/components/rooms/RoomRow/RoomRow.stories.tsx, src/frontend/magnify/src/components/rooms/RoomRow/RoomRow.test.tsx, src/frontend/magnify/src/components/rooms/RoomRow/RoomRow.tsx, src/frontend/magnify/src/components/rooms/RoomRow/index.ts, src/frontend/magnify/src/controller/default.controller.ts, src/frontend/magnify/src/controller/interface.ts, src/frontend/magnify/src/controller/log.controller.ts, src/frontend/magnify/src/controller/mock.controller.ts, src/frontend/magnify/src/factories/room.ts, src/frontend/magnify/src/types/room.ts, src/frontend/magnify/src/utils/DebugRoute.tsx, src/frontend/yarn.lock
This is an atomic block to build the list of the
rows. It needed also a loading button, so I added it too.
It is also the first try of using the controller in an actual component
=> Create a component do display and join a room

src/frontend/scripts/src/generateComponent.ts, src/frontend/scripts/src/generateIcon.ts
Fix the #40 bug.
Now the test file created is a `.test.tsx` file.
=> Right test file created in dev scripts

src/frontend/magnify/src/components/design-system/SquareAvatar/SquareAvatar.stories.tsx, src/frontend/magnify/src/components/design-system/SquareAvatar/SquareAvatar.test.tsx, src/frontend/magnify/src/components/design-system/SquareAvatar/SquareAvatar.tsx
If a user has no avatar, we should display something.
Here is an attempt to display his first letters
=> Add fallback for avatar

src/frontend/demo/src/App.tsx, src/frontend/demo/src/index.tsx, src/frontend/demo/src/views/rooms.tsx, src/frontend/magnify/.storybook/preview.js, src/frontend/magnify/src/components/design-system/RowsList/RowsList.tsx, src/frontend/magnify/src/components/design-system/WaitingRow/WaitingRow.stories.tsx, src/frontend/magnify/src/components/design-system/WaitingRow/WaitingRow.test.tsx, src/frontend/magnify/src/components/design-system/WaitingRow/WaitingRow.tsx, src/frontend/magnify/src/components/design-system/WaitingRow/index.ts, src/frontend/magnify/src/components/design-system/index.ts, src/frontend/magnify/src/components/index.ts, src/frontend/magnify/src/components/rooms/MyRooms/MyRooms.stories.tsx, src/frontend/magnify/src/components/rooms/MyRooms/MyRooms.test.tsx, src/frontend/magnify/src/components/rooms/MyRooms/MyRooms.tsx, src/frontend/magnify/src/components/rooms/MyRooms/index.ts, src/frontend/magnify/src/components/rooms/RegisterRoom/RegisterRoom.stories.tsx, src/frontend/magnify/src/components/rooms/RegisterRoom/RegisterRoom.test.tsx, src/frontend/magnify/src/components/rooms/RegisterRoom/RegisterRoom.tsx, src/frontend/magnify/src/components/rooms/RegisterRoom/index.ts, src/frontend/magnify/src/components/rooms/RegisterRoomForm/RegisterRoomForm.stories.tsx, src/frontend/magnify/src/components/rooms/RegisterRoomForm/RegisterRoomForm.test.tsx, src/frontend/magnify/src/components/rooms/RegisterRoomForm/RegisterRoomForm.tsx, src/frontend/magnify/src/components/rooms/RegisterRoomForm/index.ts, src/frontend/magnify/src/components/rooms/index.ts, src/frontend/magnify/src/controller/default.controller.ts, src/frontend/magnify/src/controller/interface.ts, src/frontend/magnify/src/controller/log.controller.ts, src/frontend/magnify/src/controller/mock.controller.ts, src/frontend/magnify/src/factories/rooms.ts
Create a list of rooms that can be used to display the list of user's rooms
It also blink waiting for the row to load
=> Create room list

src/frontend/scripts/src/generateIcon.templates.ts, src/frontend/scripts/src/generateIcon.ts
Change the path where the icon is created to fix bug #50.
Change `svgIcons` for `design-system/svg-icons`
=> Change icon creation path

src/frontend/magnify/src/components/rooms/AddGroupToRoomDialog/AddGroupToRoomDialog.stories.tsx, src/frontend/magnify/src/components/rooms/AddGroupToRoomDialog/AddGroupToRoomDialog.test.tsx, src/frontend/magnify/src/components/rooms/AddGroupToRoomDialog/AddGroupToRoomDialog.tsx, src/frontend/magnify/src/components/rooms/AddGroupToRoomDialog/index.ts, src/frontend/magnify/src/components/rooms/index.ts, src/frontend/magnify/src/controller/default.controller.ts, src/frontend/magnify/src/controller/interface.ts, src/frontend/magnify/src/controller/log.controller.ts, src/frontend/magnify/src/controller/mock.controller.ts, src/frontend/magnify/src/factories/room.ts, src/frontend/magnify/src/types/room.ts
This form display the user's groups and the user
can add them to a select list. Then when he submits
the groups ids, they are added to the room
=> Create a form to add groups to room

src/frontend/demo/src/App.tsx, src/frontend/demo/src/views/404.tsx, src/frontend/demo/src/views/default.tsx, src/frontend/demo/src/views/groups.tsx, src/frontend/demo/src/views/profile.tsx, src/frontend/demo/src/views/room.tsx, src/frontend/demo/src/views/rooms.tsx, src/frontend/magnify/src/components/design-system/RowsList/RowsList.tsx, src/frontend/magnify/src/components/meetings/MeetingRow/MeetingRow.tsx, src/frontend/magnify/src/components/rooms/RoomOverview/RoomOverview.stories.tsx, src/frontend/magnify/src/components/rooms/RoomOverview/RoomOverview.test.tsx, src/frontend/magnify/src/components/rooms/RoomOverview/RoomOverview.tsx, src/frontend/magnify/src/components/rooms/RoomOverview/index.ts, src/frontend/magnify/src/components/rooms/index.ts, src/frontend/magnify/src/controller/default.controller.ts, src/frontend/magnify/src/controller/interface.ts, src/frontend/magnify/src/controller/log.controller.ts, src/frontend/magnify/src/controller/mock.controller.ts, src/frontend/magnify/src/factories/meetings.ts, src/frontend/magnify/src/factories/room.ts, src/frontend/magnify/src/types/room.ts
There is two view of a room: an overview with groups and
meetings, and another with advanced configuration. This create
the overview
=> Create an overview of a room

src/frontend/demo/src/App.tsx, src/frontend/demo/src/views/roomSettings.tsx, src/frontend/magnify/src/components/design-system/Section/Section.stories.tsx, src/frontend/magnify/src/components/design-system/Section/Section.test.tsx, src/frontend/magnify/src/components/design-system/Section/Section.tsx, src/frontend/magnify/src/components/design-system/Section/index.ts, src/frontend/magnify/src/components/design-system/Toggle/Toggle.stories.tsx, src/frontend/magnify/src/components/design-system/Toggle/Toggle.test.tsx, src/frontend/magnify/src/components/design-system/Toggle/Toggle.tsx, src/frontend/magnify/src/components/design-system/Toggle/index.ts, src/frontend/magnify/src/components/design-system/index.ts, src/frontend/magnify/src/components/rooms/RoomConfig/RoomConfig.stories.tsx, src/frontend/magnify/src/components/rooms/RoomConfig/RoomConfig.test.tsx, src/frontend/magnify/src/components/rooms/RoomConfig/RoomConfig.tsx, src/frontend/magnify/src/components/rooms/RoomConfig/index.ts, src/frontend/magnify/src/components/rooms/RoomSettingToggle/RoomSettingToggle.stories.tsx, src/frontend/magnify/src/components/rooms/RoomSettingToggle/RoomSettingToggle.test.tsx, src/frontend/magnify/src/components/rooms/RoomSettingToggle/RoomSettingToggle.tsx, src/frontend/magnify/src/components/rooms/RoomSettingToggle/index.ts, src/frontend/magnify/src/components/rooms/RoomSettingsBlock/RoomSettingsBlock.stories.tsx, src/frontend/magnify/src/components/rooms/RoomSettingsBlock/RoomSettingsBlock.test.tsx, src/frontend/magnify/src/components/rooms/RoomSettingsBlock/RoomSettingsBlock.tsx, src/frontend/magnify/src/components/rooms/RoomSettingsBlock/index.ts, src/frontend/magnify/src/components/rooms/index.ts, src/frontend/magnify/src/controller/default.controller.ts, src/frontend/magnify/src/controller/interface.ts, src/frontend/magnify/src/controller/log.controller.ts, src/frontend/magnify/src/controller/mock.controller.ts, src/frontend/magnify/src/factories/room.ts, src/frontend/magnify/src/types/room.ts
Implement components to manage room settings as discussed on issue #39.
Provide several components and sections.
- Toggle components
- A toggle component
- A toggle component specialized for rooms
- A Toggle block component
One difficulty is that we do not know which settings will be done on the jitsi side, and which settings we will implement in the back.
For now I added 7 setings that come from the design.
=> Room configuration components

src/frontend/magnify/package.json, src/frontend/magnify/src/components/design-system/ActivableButton/ActivableButton.stories.tsx, src/frontend/magnify/src/components/design-system/ActivableButton/ActivableButton.tsx, src/frontend/magnify/src/components/design-system/ActivableButton/index.ts, src/frontend/magnify/src/components/design-system/CalendarInput/CalendarInput.stories.tsx, src/frontend/magnify/src/components/design-system/CalendarInput/CalendarInput.test.tsx, src/frontend/magnify/src/components/design-system/CalendarInput/CalendarInput.tsx, src/frontend/magnify/src/components/design-system/CalendarInput/index.ts, src/frontend/magnify/src/components/design-system/Fieldset/Fieldset.stories.tsx, src/frontend/magnify/src/components/design-system/Fieldset/Fieldset.test.tsx, src/frontend/magnify/src/components/design-system/Fieldset/Fieldset.tsx, src/frontend/magnify/src/components/design-system/Fieldset/index.ts, src/frontend/magnify/src/components/design-system/TextField/TextField.tsx, src/frontend/magnify/src/components/design-system/index.ts, src/frontend/magnify/src/components/index.ts, src/frontend/magnify/src/components/meetings/CreateMeetingForm/CreateMeetingForm.stories.tsx, src/frontend/magnify/src/components/meetings/CreateMeetingForm/CreateMeetingForm.test.tsx, src/frontend/magnify/src/components/meetings/CreateMeetingForm/CreateMeetingForm.tsx, src/frontend/magnify/src/components/meetings/CreateMeetingForm/index.ts, src/frontend/magnify/src/components/meetings/index.ts, src/frontend/magnify/src/components/sidebar/SidebarButton/SidebarButton.tsx, src/frontend/magnify/src/controller/default.controller.ts, src/frontend/magnify/src/controller/interface.ts, src/frontend/magnify/src/controller/log.controller.ts, src/frontend/magnify/src/controller/mock.controller.ts, src/frontend/magnify/src/hooks/useFormState.ts
A form to create a new meeting. It comes with a few new inputs components and refactoring
=> Create add meeting to room form

src/frontend/magnify/src/components/rooms/RoomSettingsBlock/RoomSettingsBlock.tsx
Fix bug #63.
Removal of containing box by builting an array.
=> 🐛(frontend) fix broken grid structure

src/frontend/demo/src/App.tsx, src/frontend/demo/src/views/myMeetings.tsx, src/frontend/magnify/src/components/meetings/MeetingRow/index.ts, src/frontend/magnify/src/components/meetings/MyMeetings/MyMeetings.stories.tsx, src/frontend/magnify/src/components/meetings/MyMeetings/MyMeetings.test.tsx, src/frontend/magnify/src/components/meetings/MyMeetings/MyMeetings.tsx, src/frontend/magnify/src/components/meetings/MyMeetings/index.ts, src/frontend/magnify/src/components/meetings/index.ts, src/frontend/magnify/src/controller/default.controller.ts, src/frontend/magnify/src/controller/interface.ts, src/frontend/magnify/src/controller/log.controller.ts, src/frontend/magnify/src/controller/mock.controller.ts
A new view to show the user's meetings
Just an additional route, and a list of meetings
using always the same rowList abstraction
=> ✨(frontlib) create a view to list my meetings

src/frontend/magnify/src/components/rooms/RoomOverview/RoomOverview.test.tsx, src/frontend/magnify/src/components/rooms/RoomOverview/RoomOverview.tsx, src/frontend/magnify/src/components/rooms/RoomRow/RoomRow.tsx
There were still a few links missing between pages. Here is a fix
Links added:
- Links from room row to room settings
- Links from room row to room overview
- Links from room overview to room settings
- Links from room overview to jitsi view
=> Add missing links between views

renovate.json
The renovate json configuration file was malformed. We fix it.
=> 🔧(renovate) fix configuration file

src/frontend/magnify/src/components/jitsi/MagnifyMeeting/index.tsx, src/frontend/magnify/src/components/rooms/RoomConfig/RoomConfig.tsx, src/frontend/magnify/src/types/entities/room/index.ts, src/frontend/magnify/src/utils/constants/jitsi/Events.ts
Give the possibility to configure a password when arriving in the room
=> ✨(frontend) add password to room

src/frontend/magnify/src/services/http/http.service.ts, src/frontend/magnify/src/services/users/users.repository.ts
sessionStorage only has current tab as context. We move into localStorage
=> ♻️(frontend) move auth token in localStorage

src/frontend/demo/src/views/profile/account/index.tsx, src/frontend/magnify/src/components/profile/IdentityBlock/IdentityBlock.tsx
Some features such as avatar upload or account deletion are not yet available. They are therefore not displayed to the user.
=> ♻️(frontend) update account page

src/frontend/magnify/apps/magnify-site/src/components/AppRouter/index.tsx, src/frontend/magnify/apps/magnify-site/src/components/DefaultProvider/index.tsx, src/frontend/magnify/apps/magnify-site/src/utils/routes/rooms/index.tsx, src/frontend/magnify/apps/magnify-site/src/utils/routes/root/index.tsx
We want the list of rooms to be at the root '/' so that it is the most ISO with 
the current site
=> ✨(frontend) change home url

src/frontend/magnify/apps/magnify-site/src/i18n/commonMessages.ts, src/frontend/magnify/apps/magnify-site/src/views/rooms/settings/index.tsx, src/frontend/magnify/packages/components/src/components/design-system/Layout/Header/Avatar/ResponsiveLayoutHeaderAvatar.tsx, src/frontend/magnify/packages/components/src/components/design-system/Modal/ErrorRequest/MagnifyErrorRequestModal.tsx, src/frontend/magnify/packages/components/src/components/rooms/RegisterRoomForm/RegisterRoomForm.tsx, src/frontend/magnify/packages/components/src/components/rooms/RoomConfig/RoomConfig.tsx, src/frontend/magnify/packages/components/src/components/rooms/RoomRow/RoomRow.tsx, src/frontend/magnify/packages/components/src/components/users/row/base/RowUserBase.tsx, src/frontend/magnify/packages/components/src/context/modals/index.tsx, src/frontend/magnify/packages/components/src/hooks/useErrors.tsx, src/frontend/magnify/packages/components/src/services/keycloak/keycloak.service.ts
A few small bugs or annoying points were listed before the start of production.
=> 🐛(frontend) fix and add many points for the first release 

CHANGELOG.md, Makefile
Make the text look prettier
##Description...
The help comments text looked inconsistent with upper and lower cases.
Use uppercase at the start of each line.
=> 💬(makefile) capitalize the first letter

README.md
Previously, it was challenging to contribute to the project easily, especially when it came to understanding the frontend part. In addition to the architecture changes made in a previous pull request, we needed to add a new section to the README.md file to describe how to launch and contribute to the frontend project.
=> 📝(frontend) update README.md

src/frontend/packages/core/src/components/design-system/Modal/index.test.tsx, src/frontend/packages/core/src/components/design-system/Modal/index.tsx
A translation error has crept into the MagnifyModal component
=> 🚑️(frontend) fix MagnifyModal

Makefile
Make commands related to frontend are broken
- Add install-front into make-bootstrap
Close #218
=> ✨(frontend) fix make commands related to frontend

Makefile, setup.cfg, src/frontend/packages/core/src/components/users/row/base/RowUserBase.test.tsx, src/frontend/packages/core/src/components/users/row/base/RowUserBase.tsx
Resolve #231, close #231 
Related to the issue #231
The proposed solution is to replace the missing menu with an empty Box component.
=> Issue#231  align selects on list of meeting members
