CHANGELOG.md
README.md
env.d/development/common
src/backend/magnify/core/views.py
src/backend/magnify/settings.py
src/backend/magnify/tests/test_redirect.py

In token, "sub" field is the xmpp domain of server.
So this should be an env variable as it depends on which jitsi instance we want magnify to deliver tokens to

Add token "sub" field to env, as "jitsi_xmpp_domain"

---

.circleci/config.yml

We recently switched to new circle node images and upgraded to node 16 which has also upgraded npm to version 8.11.0. This has broken the publish command so we have to fix it.
Copy of @jbpenrath's fix on richie: https://github.com/openfun/richie/pull/1734/commits/ad1e22f10cfa05ec76f594644301a38b6a00ba4d

💚(circleci) fix npm job

---

src/magnify/apps/core/serializers/users.py
tests/apps/core/test_api_users.py

We forgot to call save on the user instance after setting its password which resulted in the password being set without hashing. It was not functional.
The test had a blind spot and should check that the password was correctly set.
Instead of adding a call to  `save` after setting the password using `set_password`, we compute the encoded password directly and pass it to the save method so that we don't need to save the user twice.
More importantly, it also avoids saving the raw password to database in the first save, only to overwrite it in the second save :sweat_smile:

🐛(serializers) fix setting user password upon creation

---

src/magnify/apps/core/api.py
src/magnify/apps/core/permissions.py
src/magnify/apps/core/urls.py
tests/apps/core/test_core_api_room_group_relations.py
tests/apps/core/test_core_api_room_user_relations.py

We want to use api urls in the form `/api/rooms/{room.id}/users/{user.id}/`

🎨(backend) use REST style api path for RoomUser and RoomGroup

---

src/magnify/apps/core/api.py
src/magnify/apps/core/factories.py
src/magnify/apps/core/migrations/0001_initial.py
src/magnify/apps/core/models.py
src/magnify/apps/core/permissions.py
src/magnify/apps/core/serializers/__init__.py
src/magnify/apps/core/serializers/rooms.py
tests/apps/core/test_core_api_room_group_relations.py
tests/apps/core/test_core_api_room_user_relations.py
tests/apps/core/test_core_api_rooms.py
tests/apps/core/test_core_models_meeting_group_relations.py
tests/apps/core/test_core_models_meeting_user_relations.py
tests/apps/core/test_core_models_room_group_relations.py
tests/apps/core/test_core_models_room_user_relations.py

RoomUser is confusing, as it is not an actual user.
Same for RoomGroup.
They have been renamed to RoomUserAccess and RoomGroupAccess.

🚚(backend) rename Room relation to access

---

src/magnify/apps/core/models.py
src/magnify/apps/core/serializers/meetings.py
src/magnify/apps/core/serializers/rooms.py
tests/apps/core/test_core_api_rooms.py
tests/apps/core/test_core_api_rooms_meetings.py

The Jitsi rooms should contain the name of the related Magnify room but still be unique. We need to add this information in the rooms/meetings detail objects returned by the API so the front knows where to connect.
The easiest way is to suffix it with the object's UID which is sure to be unique.
This should not appear in the Jitsi Meet UI as the display is shortened with "..." but we may also be able to hide the Jitsi room from the Jitsi UI when opened inside Magnify.

✨(api) add jitsi room name to API and ensure their unicity

---

src/frontend/magnify/src/components/meetings/CreateMeetingForm/CreateMeetingForm.stories.tsx
src/frontend/magnify/src/components/meetings/CreateMeetingForm/CreateMeetingForm.test.tsx
src/frontend/magnify/src/components/meetings/CreateMeetingForm/CreateMeetingForm.tsx
src/frontend/magnify/src/components/rooms/CreateMeetingInRoomDialog/CreateMeetingInRoomDialog.stories.tsx
src/frontend/magnify/src/components/rooms/CreateMeetingInRoomDialog/CreateMeetingInRoomDialog.test.tsx
src/frontend/magnify/src/components/rooms/CreateMeetingInRoomDialog/CreateMeetingInRoomDialog.tsx
src/frontend/magnify/src/components/rooms/CreateMeetingInRoomDialog/index.ts
src/frontend/magnify/src/components/rooms/RoomOverview/RoomOverview.tsx
src/frontend/magnify/src/components/rooms/index.ts

Enables to add groups and meetings in the room overview.
- Linking the current `AddGroupToRoomDialog` to the `onAdd` prop of the `RowsList`
- Add a `CreateMeetingInRoomDialog` that uses the `CreateMeetingForm`, and linking it to the `onAdd` prop of the `RowsList`

Enable to add existing group / to create meeting in a room

---

src/frontend/demo/src/App.tsx
src/frontend/demo/src/views/group.tsx
src/frontend/magnify/src/components/groups/AddUserForm/AddUserForm.stories.tsx
src/frontend/magnify/src/components/groups/AddUserForm/AddUserForm.test.tsx
src/frontend/magnify/src/components/groups/AddUserForm/AddUserForm.tsx
src/frontend/magnify/src/components/groups/AddUserForm/index.ts
src/frontend/magnify/src/components/groups/GroupRow/GroupRow.test.tsx
src/frontend/magnify/src/components/groups/GroupRow/GroupRow.tsx
src/frontend/magnify/src/components/groups/GroupUserList/GroupUserList.stories.tsx
src/frontend/magnify/src/components/groups/GroupUserList/GroupUserList.test.tsx
src/frontend/magnify/src/components/groups/GroupUserList/GroupUserList.tsx
src/frontend/magnify/src/components/groups/GroupUserList/index.ts
src/frontend/magnify/src/components/groups/GroupsList/GroupsList.test.tsx
src/frontend/magnify/src/components/groups/MyGroupsBlock/MyGroupsBlock.test.tsx
src/frontend/magnify/src/components/groups/index.ts
src/frontend/magnify/src/controller/default.controller.ts
src/frontend/magnify/src/controller/interface.ts
src/frontend/magnify/src/controller/log.controller.ts
src/frontend/magnify/src/controller/mock.controller.ts

This is straight forward. We use the abstractions we previously build
to add a form, a dialog and a list of users to present a single group

Add a view to present a single group and add users

---

src/frontend/magnify/src/components/groups/AddGroupForm/AddGroupForm.stories.tsx
src/frontend/magnify/src/components/groups/AddGroupForm/AddGroupForm.test.tsx
src/frontend/magnify/src/components/groups/AddGroupForm/AddGroupForm.tsx
src/frontend/magnify/src/components/groups/AddGroupForm/index.ts
src/frontend/magnify/src/components/groups/GroupsList/GroupsList.test.tsx
src/frontend/magnify/src/components/groups/GroupsList/GroupsList.tsx
src/frontend/magnify/src/components/groups/index.ts
src/frontend/magnify/src/controller/default.controller.ts
src/frontend/magnify/src/controller/interface.ts
src/frontend/magnify/src/controller/log.controller.ts
src/frontend/magnify/src/controller/mock.controller.ts

A form to create a new group with it's name. As a v1, we can add users afterward
Nothing unexpected here too. We just complete the onAdd prop
of the row list abstraction to open a popup.

✨(frontlib) add a form to create a new group

---

src/frontend/magnify/src/components/meetings/MyMeetings/MyMeetings.test.tsx
src/frontend/magnify/src/components/sidebar/MagnifySidebar/MagnifySidebar.tsx

As discussed with the designer, this link was added
without any specific intention of a view, so as long as we
do not have any view, I think we should let this link

🗑️(frontlib) delete an unused settings link

---

sandbox/settings.py

When trying to login to the Django admin site, we get a CSRF 403 error page:
- Fix `CSRF_TRUSTED_ORIGINS` setting in Development environment
- set the security key via the environment variable and not in the setting file

Fix csrf error on admin page

---

setup.cfg

Since the release of djangorestframework 3.14.0, drf-yasg 1.20.0 does not work properly, so we have to upgrade this package to its latest version to fix this issue.

⬆️(backend) upgrade drf-yasg to version 1.21.4

---

CHANGELOG.md
sandbox/settings.py
setup.cfg

Install django-cors-headers to allow CORS requests from authorized domains on production and from everywhere on development

✨(backend) enable cors headers

---

src/magnify/apps/core/api/rooms.py
tests/apps/core/test_core_api_rooms.py
tests/apps/core/test_core_models_meetings_get_occurences.py

Calls to the room detail API endpoint may contain accents and upper case letters in the room name. We want to normalize them to the slug we save in room names.
Said differently "Réunion" and "reunion" should be the same room.

🐛(api) normalize room names in API calls

---

src/frontend/magnify/src/i18n/TranslationProvider/TranslationsProvider.tsx
src/frontend/magnify/src/services/http/http.service.ts

Currently, the messages sent by the back are conditioned by the language of the browser. To make the messages sent by the back correspond to the language chosen by the user and not to the language of the browser we update the headers

✨(frontend) set current lang request headers

---

src/frontend/magnify/src/components/rooms/MyRooms/MyRooms.test.tsx
src/frontend/magnify/src/components/rooms/MyRooms/MyRooms.tsx

When the user had not yet created a room, no message was displayed to indicate this fact and the section containing the list of rooms was left blank.

✨ (frontend) display message when the list of rooms is empty

---

src/frontend/magnify/src/components/rooms/RoomRow/RoomRow.test.tsx
src/frontend/magnify/src/components/rooms/RoomRow/RoomRow.tsx

There was no option in the room settings to copy the link of a room to the clipboard in order to share it for example.

✨(frontend) add a copy room link item to roomRow menu

---

.circleci/config.yml
src/magnify/apps/core/api/rooms.py
src/magnify/apps/core/factories.py
src/magnify/apps/core/models.py
src/magnify/apps/core/permissions.py
src/magnify/apps/core/serializers/rooms.py
tests/apps/core/test_core_api_room_user_access.py
tests/apps/core/test_core_api_rooms.py
tests/apps/core/test_core_models_meeting_user_access.py
tests/apps/core/test_core_models_room_user_access.py
tests/apps/core/test_core_models_rooms.py

Only administrators and owners of a room could see its related users and groups. We think all members of a room should see them.
Add "users" and "groups" fields to the payload returned on the room detail endpoint for a room's members.
I took the opportunity to refactor access rights methods and optimize the number of database query they generate.

♻️(api) show room users and groups to members on room detail endpoint

---

.circleci/config.yml

Build docker image and publish them to DockerHub after a commit to the main branch or a tag.

👷(circleci) publish docker image

---

src/frontend/magnify/apps/magnify-site/vite.config.ts

Currently the production build does not work as rollup treeshake remove from bundle the ThemeContext module provided by grommet. For now, the only workaround, we found is to disable treeshake.

🔧(magnify-site) disable treeshaking for production build

---

docs/env.md
sandbox/settings.py
src/magnify/apps/core/permissions.py
tests/apps/core/test_core_api_users.py

When relying on Keycloak or another external store of users, we want to deactivate user creation on the API and let Magnify create them on-the-fly via OIDC tokens.
Add a new setting to allow deactivating user creation via the API

✨(users) allow deactivating the creation of users via the API

---

src/magnify/apps/core/factories.py

Usernames and room slugs are unique in database but Faker can sometimes generate 2 objects with the same value for these fields.
To prevent this we introduce a `UniqueFaker` util.

💚(factories) fix randomly failing tests due to fields uniqueness

---

docs/env.md
sandbox/settings.py
setup.cfg

We want to allow setting the default language via environment variables.
Add a Django Configuration value for the `LANGUAGE_CODE` setting and update the docs.

Allow setting default language

---

CHANGELOG.md
src/frontend/magnify/apps/magnify-site/src/views/rooms/jitsi/index.tsx
src/frontend/magnify/packages/components/src/components/jitsi/MagnifyMeeting/index.tsx

Depending on the jitsi server settings, the name used is either invalid or not the one used to sign the JWT token.

🐛(frontend) use jitsi name from back

---

docs/env.md
env.d/demo
src/magnify/apps/core/migrations/0002_alter_user_email.py

The demo stack was broken because it uses Production settings but we did not set CSRF trusted origins.
Set `CSRF_TRUSTED_ORIGINS` in the demo environment.

🔧(demo) set CSRF_TRUSTED_ORIGINS for the demo

---

CHANGELOG.md
src/frontend/magnify/packages/components/src/components/design-system/Layout/SimpleLayout/SimpleLayout.tsx

The `overflow: scroll` property was initially added to the `SimpleLayout` component  to handle the case when its height exceeds 100vh. This commit changes it to `auto` so that the scrollbar appears only when needed.
**Before:**
Useless scrolls:
Only Y scroll useful:
**Now**

:lipstick: (apps:frontend) improve scroll behaviour of SimpleLayout

---

CHANGELOG.md
src/frontend/magnify/apps/magnify-site/src/views/rooms/settings/index.tsx

Resolves #175 
The only way to leave the room settings page was to click on the Breadcrumb. 
To improve this UX aspect we change it into a proper back link. 
We use the same link as in User settings page to be coherent accross the app.

(frontend) use 'back' link in Room settings page

---

src/frontend/magnify/apps/magnify-site/src/mocks/handlers/rooms/roomsHandlers.ts
src/frontend/magnify/apps/magnify-site/src/views/rooms/settings/index.test.tsx
src/frontend/magnify/apps/magnify-site/src/views/rooms/settings/index.tsx
src/frontend/magnify/packages/components/.storybook/preview.tsx
src/frontend/magnify/packages/components/src/components/design-system/Formik/ValuesChange/FormikValuesChange.tsx
src/frontend/magnify/packages/components/src/components/rooms/MyRooms/MyRooms.stories.tsx
src/frontend/magnify/packages/components/src/components/rooms/MyRooms/MyRooms.test.tsx
src/frontend/magnify/packages/components/src/components/rooms/RegisterRoom/RegisterRoom.test.tsx
src/frontend/magnify/packages/components/src/components/rooms/RoomConfig/RoomConfig.stories.tsx
src/frontend/magnify/packages/components/src/components/rooms/RoomConfig/RoomConfig.test.tsx
src/frontend/magnify/packages/components/src/components/rooms/RoomConfig/RoomConfig.tsx
src/frontend/magnify/packages/components/src/components/rooms/RoomConfig/Users/RoomUsersConfig.stories.tsx
src/frontend/magnify/packages/components/src/components/rooms/RoomConfig/Users/RoomUsersConfig.test.tsx
src/frontend/magnify/packages/components/src/components/rooms/RoomRow/RoomRow.stories.tsx
src/frontend/magnify/packages/components/src/components/rooms/RoomRow/RoomRow.test.tsx
src/frontend/magnify/packages/components/src/factories/rooms/index.ts
src/frontend/magnify/packages/components/src/mocks/allHandlers/rooms/roomsHandlers.ts
src/frontend/magnify/packages/components/src/services/routes/RoutesBuilder.service.ts
src/frontend/magnify/packages/components/src/types/entities/room/index.ts

Currently, when we create a room, this room is automatically private. We must be able to have the choice to make this room public or private. 
We add a switch to the room settings page.

✨(frontend) allow public or private room

---

docs/env.md
sandbox/settings.py
src/magnify/apps/core/models.py
tests/apps/core/test_core_models_meetings.py
tests/apps/core/test_core_models_rooms.py

We may want to namespace room names in the same Jitsi instance or we may want to include a text in the room names.
- Add a prefix to the Jitsi room name for both the Meeting and Room models
- Allow setting the Jitsi room prefix by setting the `MAGNIFY_JITSI_ROOM_PREFIX` environment variable
- Update the environment variables documentation to add the new setting

✨(jitsi) allow adding a prefix to the Jitsi room names

---

docs/env.md
sandbox/settings.py
src/frontend/packages/core/src/components/rooms/RoomConfig/RoomConfig.tsx
src/frontend/packages/core/src/types/entities/room/index.ts
src/magnify/apps/core/api/rooms.py
src/magnify/apps/core/models.py
tests/apps/core/api/rooms/test_core_api_rooms_list.py
tests/apps/core/test_core_models_rooms.py

Currently, public rooms are listed on every users' dashboard. Although we want every user be able to join a public room, we don't want them to see it in their personal list of rooms.
We want rooms to be private by default (even better make it configurable via settings)
Finally, the Jitsi parameter to start with audio muted does not work.

Hide public rooms from list endpoint

---

src/frontend/packages/core/src/components/rooms/RoomConfig/RoomConfig.tsx

It appears that it makes more sens to list this switch in the security section.
Move widget to the security section.

🚸(frontend) move room public switch to the security section

---

src/frontend/packages/core/src/components/design-system/Layout/SimpleLayout/SimpleLayout.tsx

Currently the illustration section has a padding of 2rem all around so the illustration used does not stick on edges that look visually weird.
- Remove the padding: 2rem to the illustration box component.
- Display the illustration through CSS with background-image and keep only the FUN Logo as image.
Close #213

🐛️(frontend) fix SimpleLayout

---

src/frontend/packages/core/src/components/rooms/RoomConfig/RoomConfig.tsx

In room settings view, user is able to protect access to its room through a password. Currently the input field to set the password is a text input so its value is always visible that is weird.
- Add type='password' 
Close #216

✨(frontend) Allow room administrator to show / hide input password

---

src/frontend/packages/core/src/views/rooms/settings/index.test.tsx
src/frontend/packages/core/src/views/rooms/settings/index.tsx

When a room is marked as public, its list of members is hidden
Make the "Members" section always visible and functional.
Secure behavior with a test.
Close #219

✨(frontend) Make the "Members" section always visible and functional

---

setup.cfg
src/magnify/apps/core/factories.py

Since django-timezone-field version 6, the static method `get_default_zoneinfo_tzs` has been removed from the class TimeZoneField. As we were using this method within our factories, our test suites were broken. So we decide to install pytz and retrieve all existing timezones from this library to replace the deprecated method.

✅(backend) replace deprecated TimeZoneField.get_default_zoneinfo_tzs
